### ISSUE TITLE
in the "Define title" window, there is no default action when you press enter.

### ISSUE THREAD

**Issue by jeremyp3** [mate-desktop/mate-terminal#449] opened 2023-11-22 16:01 UTC
#### Expected behaviour
after entering a title and pressing the enter key, close the window and display the title as when you click on the OK button.

#### Actual behaviour
pressing the Enter key after writing a title takes no action and the window remains open

#### Steps to reproduce the behaviour
1. open mate-terminal
2. press ctrl + t or terminal menu / edit title
3. enter title
4. press enter

#### MATE general version
1.26.2

#### Package version
mate-terminal 1.26.1-1        

#### Linux Distribution
Debian testing

**Comment by cwendling** [comment] 2023-11-22 16:33
It is already implemented in #394, and #421 and #435 are duplicate of this. It'll be in the next release.

**Closed by cwendling** 2023-11-22 16:33 UTC

**Comment by timbly5000** [comment] 2024-04-03 08:35
Just out of interest, how did this get broken? Set title / enter key has been working for the past 20+ years.
