### ISSUE TITLE
[Feature Request] Set Title dialog: Accept input with Enter key

### ISSUE THREAD

**Issue by Gydo194** [mate-desktop/mate-terminal#435] opened 2023-06-30 15:10 UTC
#### Background to request
I often use custom window and tab titles to keep my terminals organized.
When setting a tab title, the user has to click the 'OK' button on the 'Set Title' dialog. 
It feels like I can just hit enter to accept the dialog, but I have to click the button instead.

#### Expected behaviour
When changing the title of a window or tab, the 'Set Title' dialog should accept the user's input when the user presses enter.

#### Actual behaviour
The enter key is ignored, forcing the user to press the 'OK' button using the mouse.

**Comment by Gydo194** [comment] 2023-06-30 15:12
I'd like to work on this myself, as my first contribution to MATE.

**Comment by lukefromdc** [comment] 2023-06-30 18:51
Go for it, we can always use more coders

**Comment by allanlaal** [comment] 2023-06-30 23:05
isnt this fixed in 1.27 ?

**Comment by cwendling** [comment] 2023-07-01 09:57
It is already fixed indeed, see #394, and #421 is also a duplicate of this.

No worries, but please try and check the issues (even closed), and test the development branch ;)
This said, if it's still broken in the dev branch (e.g. the fix doesn't work anymore), that's another story -- and please mention it so we know it's a regression :)

**Closed by cwendling** 2023-07-01 09:57 UTC

**Comment by Gydo194** [comment] 2023-07-01 13:44
Oops, sorry for the duplicate. I completely missed those issues while searching.
And it does indeed work after installing from source.. My bad.
